# Generated by Django 5.1.4 on 2026-04-26 19:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0001_initial'),
        ('escolas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='submissoes/')),
                ('nota_calculada', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nota_professor_override', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('categoria_erro_analytics', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback_ia', models.TextField(blank=True, null=True)),
                ('feedback_professor', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROCESSAMENTO', 'Em processamento'), ('CORRIGIDA', 'Corrigida'), ('REVISADA_PROFESSOR', 'Revisada pelo professor'), ('CONFLITO_SYNC', 'Conflito de sincronização')], default='PENDENTE', max_length=25)),
                ('timestamp_local', models.DateTimeField(blank=True, null=True)),
                ('server_time_snapshot', models.DateTimeField(blank=True, null=True)),
                ('client_server_offset_ms', models.IntegerField(blank=True, null=True)),
                ('atividade_updated_at_snapshot', models.DateTimeField(blank=True, null=True)),
                ('observacao_resolucao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'role': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to=settings.AUTH_USER_MODEL)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to='atividades.exercicio')),
                ('override_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatDuvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagens', models.JSONField(default=list)),
                ('contador_mensagens_aluno', models.IntegerField(default=0)),
                ('submissao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='submissoes.submissao')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioCadastroMassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_original', models.FileField(upload_to='cadastros_massa/')),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PROCESSANDO', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_cadastro', to='escolas.turma')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status'], name='idx_rel_cad_status')],
            },
        ),
        migrations.AddIndex(
            model_name='submissao',
            index=models.Index(fields=['aluno', 'status'], name='idx_sub_aluno_status'),
        ),
        migrations.AddIndex(
            model_name='submissao',
            index=models.Index(fields=['exercicio', 'status'], name='idx_sub_ex_status'),
        ),
        migrations.AddIndex(
            model_name='submissao',
            index=models.Index(condition=models.Q(('categoria_erro_analytics__isnull', False)), fields=['categoria_erro_analytics'], name='idx_sub_cat_erro'),
        ),
        migrations.AlterUniqueTogether(
            name='submissao',
            unique_together={('aluno', 'exercicio')},
        ),
    ]
