# Generated by Django 5.1.4 on 2026-04-26 19:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('disciplina', models.CharField(max_length=100)),
                ('tipo_atividade', models.CharField(choices=[('EXERCICIO', 'Exercício'), ('PROVA', 'Prova')], max_length=10)),
                ('peso', models.PositiveIntegerField(blank=True, null=True)),
                ('status_publicacao', models.CharField(choices=[('DRAFT', 'Rascunho'), ('AGENDADO', 'Agendado'), ('PUBLICADO', 'Publicado')], default='DRAFT', max_length=15)),
                ('data_liberacao', models.DateTimeField(blank=True, null=True)),
                ('data_limite', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_criadas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='escolas.turma')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('MULTIPLA_ESCOLHA', 'Múltipla escolha'), ('DISSERTATIVA', 'Dissertativa')], max_length=20)),
                ('enunciado', models.TextField()),
                ('gabarito_esperado', models.TextField()),
                ('alternativas', models.JSONField(blank=True, null=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='atividades.atividade')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='MaterialApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='materiais/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_enviados', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='escolas.turma')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NotaAtividadeAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_override', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'role': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='notas_consolidadas_override', to=settings.AUTH_USER_MODEL)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_consolidadas_override', to='atividades.atividade')),
                ('override_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['turma', 'status_publicacao', 'data_liberacao'], name='idx_atv_turma_status_lib'),
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['tipo_atividade'], name='idx_atv_tipo'),
        ),
        migrations.AddConstraint(
            model_name='atividade',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('peso', 1), ('tipo_atividade', 'EXERCICIO')), models.Q(('peso__gte', 1), ('tipo_atividade', 'PROVA')), _connector='OR'), name='atv_peso_consistente'),
        ),
        migrations.AddConstraint(
            model_name='atividade',
            constraint=models.CheckConstraint(condition=models.Q(('status_publicacao', 'DRAFT'), models.Q(('data_liberacao__isnull', False), ('data_limite__isnull', False)), _connector='OR'), name='atv_datas_consistentes'),
        ),
        migrations.AddIndex(
            model_name='exercicio',
            index=models.Index(fields=['atividade'], name='idx_ex_atividade'),
        ),
        migrations.AddConstraint(
            model_name='exercicio',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('alternativas__isnull', False), ('tipo', 'MULTIPLA_ESCOLHA')), models.Q(('alternativas__isnull', True), ('tipo', 'DISSERTATIVA')), _connector='OR'), name='ex_alternativas_consistentes'),
        ),
        migrations.AlterUniqueTogether(
            name='exercicio',
            unique_together={('atividade', 'ordem')},
        ),
        migrations.AddIndex(
            model_name='notaatividadealuno',
            index=models.Index(fields=['atividade'], name='idx_nota_atv_atv'),
        ),
        migrations.AlterUniqueTogether(
            name='notaatividadealuno',
            unique_together={('aluno', 'atividade')},
        ),
    ]
