# Generated by Django 5.1.4 on 2026-04-26 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsavelAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'role': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis_vinculados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(limit_choices_to={'role': 'RESPONSAVEL'}, on_delete=django.db.models.deletion.CASCADE, related_name='filhos_vinculados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['aluno'], name='idx_resp_alu_aluno'), models.Index(fields=['responsavel'], name='idx_resp_alu_resp')],
                'unique_together': {('responsavel', 'aluno')},
            },
        ),
    ]
