# Generated by Django 5.1.4 on 2026-04-26 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('nome', 'cnpj')},
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ranking_pontuacao_ativo', models.BooleanField(default=False)),
                ('ranking_provas_ativo', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='escolas.escola')),
            ],
            options={
                'ordering': ['escola_id', 'nome'],
                'unique_together': {('escola', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ProfessorTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(limit_choices_to={'role': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_turma', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_professor', to='escolas.turma')),
            ],
            options={
                'indexes': [models.Index(fields=['turma'], name='idx_prof_turma_turma')],
                'unique_together': {('professor', 'turma')},
            },
        ),
    ]
